[package]
name = "ChainX"
version = "0.1.0"
authors = ["Chainpool <http://www.chainx.org>"]

[dependencies]
substrate-network = { git = "https://github.com/chainx-org/substrate" }
substrate-network-libp2p = { git = "https://github.com/chainx-org/substrate" }
substrate-runtime-primitives = { git = "https://github.com/chainx-org/substrate" }
substrate-primitives = { git = "https://github.com/chainx-org/substrate" }
substrate-client = { git = "https://github.com/chainx-org/substrate" }
substrate-client-db = { git = "https://github.com/chainx-org/substrate" }
substrate-state-db = { git = "https://github.com/chainx-org/substrate" }
substrate-state-machine = { git = "https://github.com/chainx-org/substrate" }
substrate-codec = { git = "https://github.com/chainx-org/substrate", default_features = false }
substrate-bft = { git = "https://github.com/chainx-org/substrate", default_features = false }
substrate-rpc-servers = { git = "https://github.com/chainx-org/substrate" }
ed25519 = { git = "https://github.com/chainx-org/substrate" }
serde = { version = "1.0", default_features = false }
serde_derive = { version = "1.0", optional = true }
chainx-primitives = {path = "./primitives"}
chainx-runtime = {path = "./runtime"}
chainx-executor = {path = "./executor"}
chainx-rpc = {path = "./rpc"}
chainx-pool = {path = "./pool"}
hex-literal = "0.1"
ctrlc = { version = "3.0", features = ["termination"] }
futures = "0.1.17"
tokio = "0.1.7"
log = "0.3"
env_logger = "0.5.13"
clap = "2.30.0"
rhododendron = "0.3"
exit-future = "0.1"

[workspace]
members = [
    "primitives",
    "consensus",
    "executor",
    "runtime",
    "pool",
    "rpc",
]
