[package]
name = "chainx-runtime"
version = "0.1.0"
authors = ["Chainpool"]

[lib]
crate-type = ["cdylib"]

[dependencies]
integer-sqrt = { git = "https://github.com/paritytech/integer-sqrt-rs.git", branch = "master" }
safe-mix = { version = "1.0", default_features = false}
substrate-codec = { git = "https://github.com/chainx-org/substrate", default-features = false }
substrate-codec-derive = { git = "https://github.com/chainx-org/substrate" }
substrate-primitives = { git = "https://github.com/chainx-org/substrate", default-features = false }
substrate-runtime-std = { git = "https://github.com/chainx-org/substrate", default-features = false }
substrate-runtime-io = { git = "https://github.com/chainx-org/substrate", default-features = false }
substrate-runtime-support = { git = "https://github.com/chainx-org/substrate", default-features = false }
substrate-runtime-consensus = { git = "https://github.com/chainx-org/substrate", default-features = false }
substrate-runtime-balances = { git = "https://github.com/chainx-org/substrate" , default-features = false}
substrate-runtime-council = { git = "https://github.com/chainx-org/substrate", default-features = false }
substrate-runtime-democracy = { git = "https://github.com/chainx-org/substrate", default-features = false }
substrate-runtime-executive = { git = "https://github.com/chainx-org/substrate", default-features = false }
substrate-runtime-primitives = { git = "https://github.com/chainx-org/substrate", default-features = false }
substrate-runtime-session = { git = "https://github.com/chainx-org/substrate", default-features = false }
substrate-runtime-staking = { git = "https://github.com/chainx-org/substrate", default-features = false }
substrate-runtime-system = { git = "https://github.com/chainx-org/substrate", default-features = false }
substrate-runtime-timestamp = { git = "https://github.com/chainx-org/substrate", default-features = false }
substrate-runtime-version = { git = "https://github.com/chainx-org/substrate", default-features = false }
chainx-primitives = { path = "../../primitives", default-features = false }

[features]
default = []
std = [
	"safe-mix/std",
	"substrate-codec/std",
	"substrate-primitives/std",
	"substrate-runtime-std/std",
	"substrate-runtime-io/std",
	"substrate-runtime-support/std",
	"substrate-runtime-consensus/std",
	"substrate-runtime-council/std",
	"substrate-runtime-democracy/std",
	"substrate-runtime-executive/std",
	"substrate-runtime-primitives/std",
	"substrate-runtime-session/std",
	"substrate-runtime-staking/std",
	"substrate-runtime-system/std",
	"substrate-runtime-timestamp/std",
	"substrate-runtime-version/std",
	"chainx-primitives/std",
]

[profile.release]
panic = "abort"
lto = true

[workspace]
members = []
